### PR TITLE
upkeep: gains `lifecycle` badge

### PR DESCRIPTION
**Pull request by jdhoffa**

### CODE REVIEW

**Review by AlexAxthelm — COMMENTED** [review]
@jdhoffa Why the experimental badge, rather than stable?

**Comment by jdhoffa** [comment]
No reason!

My default is experimental, but if you would prefer stable/ maturing, then happy to do that :-)

**Comment by AlexAxthelm** [comment]
I think so. I don't expect many changes moving forward, and all the stuff in the open issues is mostly improvements, not breaking changes

**Comment by AlexAxthelm** [comment]
I do believe that "maturing" is a deprecated lifecycle stage, according to their docs.

**Comment by jdhoffa** [comment]
> I do believe that "maturing" is a deprecated lifecycle stage, according to their docs.

Ah yes, I remember reading that.

I'll bump the other "maturing" repos to "stable" then :-)

**Review by AlexAxthelm — APPROVED** [review]

**Pull request merged**
