### PR TITLE
Chore/v1.0

### PR DESCRIPTION
**Pull request by AlexAxthelm**
🎉  Let's call this 1.0.0, since I believe this is feature complete

Update docs, and version bump

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
🎉

**Comment by jdhoffa** [comment]
I think before I approve a `1.0.0` version bump (keeping in mind that I have no idea how we are managing versions right now), I would like to have a call to prove to myself that I can run the API

Can you block time to go over that?

In general this feels like something we should coordinate in a tech review or something like that.

**Comment by jdhoffa** [comment]
Or not, lol

**Comment by AlexAxthelm** [comment]
@jdhoffa Merging, while noting your concerns about running. I'm labelling the R package here as 1.0.0, while the deploy script (which is a living document that reflects our current infrastructure) is not included in that classification.

I don't know of a good way to make that distinction clear off the top of my head.

**Pull request merged**
